global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'queue-gate'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'queue-gate-1:8010'
          - 'queue-gate-2:8010'

  - job_name: 'admission-worker'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'admission-worker:8020'

  - job_name: 'ticketing-core'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'ticketing-core-1:8030'
          - 'ticketing-core-2:8030'
